### PR TITLE
Improve Chinese translation.

### PR DESCRIPTION
**Pull request by yang-lile**

### CODE REVIEW

**Review by renancaraujo — APPROVED** [review]

**Review by erickzanardo — APPROVED** [review]
@impulse can you do a double check on this please?

**Comment by impulse** [comment]
@erickzanardo @renancaraujo @yang-lile I am thinking about if we should mix non-English content with Chinese content. Like the descriptions are Chinese, but the content it links to is not. It might be confusing/frustrating.

**Comment by erickzanardo** [comment]
> @erickzanardo @renancaraujo @yang-lile I am thinking about if we should mix non-English content with Chinese content. Like the descriptions are Chinese, but the content it links to is not. It might be confusing/frustrating.

Good point, I Agree!

**Comment by yang-lile** [comment]
> @erickzanardo @renancaraujo @yang-lile I am thinking about if we should mix non-English content with Chinese content. Like the descriptions are Chinese, but the content it links to is not. It might be confusing/frustrating.

This is a good idea. But I don't have Chinese tutorials or documentation. so I can only use Chinese descriptions and English content for the time being. I will learn flame and synchronize translations these English content.

**Comment by impulse** [comment]
@erickzanardo agree on _against_ or _for_ mixing?

@yang-lile I personally would prefer to only add entries that link to Chinese content. Probably the most troublesome point would be to keep both lists in sync for each new PR.

**Comment by erickzanardo** [comment]
> @erickzanardo agree on _against_ or _for_ mixing?
> 
> @yang-lile I personally would prefer to only add entries that link to Chinese content. Probably the most troublesome point would be to keep both lists in sync for each new PR.

hahaha, sorry, I agree with you, we shouldn't mix the languages.

**Comment by yang-lile** [comment]
@impulse Something likes non-English add entries that link to English content, and English content add entries that link to non-English content?

Sorry,  I do translation for the first time, if there is a problem, please give more advice.

**Comment by yang-lile** [comment]
I'm sorry that the previous translation wasn't perfect, but now I've added a directory and a link to the original text. Synchronizing two pull requests is a tedious thing, but I don't know how to optimize it.

**Comment by impulse** [comment]
> @impulse Something likes non-English add entries that link to English content, and English content add entries that link to non-English content?

如果我们加英语内容的话，每个PR都需要更新这个文件。Flame覆盖的中国市场很小，而且我不认为我们可以找到很多可以坚持这样做的中国人。

Your idea is perfectly fine considering we have a lot of entries that are just code-based projects. But given the reasons above I think it's just not feasible to do.

I am happy to update the file with table of contents and the corrections you have made for the existing entries. But I can't expect other contributors to add entries in one (or maybe more one day) language that they don't speak.

**Comment by yang-lile** [comment]
Maybe you are right, Flutter Chinese user is less, Flame user is less. I will work on my fork, until it's all translated. 感谢您的建议和帮助。

**Comment by impulse** [comment]
> Maybe you are right, Flutter Chinese user is less, Flame user is less. I will work on my fork, until it's all translated. 感谢您的建议和帮助。

没事，谢谢你的工作

**Pull request closed without merging**
