### PR TITLE
Fixes for awesome awesome

### PR DESCRIPTION
**Pull request by luanpotter**
@biesiadamich asked us to change the pattern to be `Foo bar foobar, by Bob.` (instead of `Foo bar foobar. By Bob` that we had).

### CODE REVIEW

**Comment by impulse** [comment]
Seems the linter doesn't like that. I mean we could just scrape that `By XY` thing all together. It would also require adjusting `CONTRIBUTING.md` btw.

**Comment by luanpotter** [comment]
Actually it looks like what it doesn't like are the alekhin articles entries because they don't have a description, just a name

**Comment by luanpotter** [comment]
I prefer our previous format tbh but they asked to changed it. Also I like having the `by` sections

**Comment by impulse** [comment]
I think the maintainer doesn't like the tutorial thing altogether.

Maybe we should refactor this into making it look like the repo he maintains:
https://github.com/sindresorhus/awesome-nodejs#tutorials

**Comment by luanpotter** [comment]
But not all of his entries have descriptions, look at the Articles section. it's totally akin to our Alekhin subsection.

But I'm up to any structural changes you seem fit, I'm a bit at odds and just saying: it doesn't comply, fix doesn't help us a lot. Feel free to commit to my branch or close this PR :)

**Comment by impulse** [comment]
@luanpotter I'll take a look on other awesome lists and see if there is any overlap

**Comment by luanpotter** [comment]
Thanks @impulse !

**Comment by impulse** [comment]
The awesome list maintained just commented on our main PR. I'll close this and make a new PR with all the changes requested.

**Pull request closed without merging**
