### PR TITLE
Added Spanish section and content

### PR DESCRIPTION
**Pull request by Yayo-Arellano**
Added Spanish section and content

### CODE REVIEW

**Comment by spydon** [comment]
Thanks for the PR and the work you put into it, unfortunately we were actually thinking of removing all localized files (in the main Flame repo too) since they become outdated too quickly.

**Comment by Yayo-Arellano** [comment]
No problem. Totally understand.

**Comment by spydon** [comment]
@Yayo-Arellano you don't have to close the PR though, there was an addition to the non English section that you added that would be good to keep, so just remove the Spanish file instead. :)

**Comment by Yayo-Arellano** [comment]
What do you mean? 

So instead of creating a new file with Spanish content. I add the Spanish content directly to the main README.md file? @spydon

**Comment by spydon** [comment]
> What do you mean?
> 
> So instead of creating a new file with Spanish content. I add the Spanish content directly to the main README.md file? @spydon

Aaah, I just woke up when I reviewed this PR, now I understand what it is doing.
I thought the spanish file was just a translation of the normal file, but since it is specific content I think this PR is completely fine! :)

**Pull request merged**
